exclude:
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache

# Build settings
remote_theme: daviddarnes/alembic@main
plugins: 
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache

title: Fyrox
encoding: utf-8
email: d1maxa@yandex.ru
description: "Fyrox is a feature-rich and easy-to-use game engine written in Rust programming language"
baseurl: ""
url: "rg3d.rs"
repo: "https://github.com/FyroxEngine/Fyrox"

sass:
  style: compressed 

social_links: 
 Twitter: https://twitter.com/DmitryNStepanov
 GitHub: https://github.com/mrDIMAS

twitter:
  username: DmitryNStepanov

navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: "View on GitHub"
  url: https://github.com/FyroxEngine/Fyrox
- title: Sponsor
  url: https://www.patreon.com/mrdimas

logo: "/assets/logos/logo.png"

navigation_footer:
- title: Created by Dmitry Stepanov
  url: https://github.com/mrDIMAS

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "RG3D news"
    feature_image: "/assets/light.jpg"

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/logos/logo2.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
