exclude:
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache

# Build settings
remote_theme: daviddarnes/alembic
plugins: 
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache

title: rg3d
encoding: utf-8
email: d1maxa@yandex.ru
description: "rg3d is a feature-rich and easy-to-use game engine written in Rust programming language"
baseurl: ""
url: "rg3d.rs"
repo: "https://github.com/mrDIMAS/rg3d"
css_inline: true

sass:
  style: compressed 

social_links: 
 Twitter: https://twitter.com/DmitryNStepanov
 GitHub: https://github.com/mrDIMAS

twitter:
  username: DmitryNStepanov

navigation_header:
- title: Home
  url: /
- title: "View on GitHub"
  url: https://github.com/mrDIMAS
- title: Sponsor
  url: https://www.patreon.com/mrdimas

navigation_footer:
- title: Created by Dmitry Stepanov
  url: https://github.com/mrDIMAS

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages